### ISSUE TITLE
Do you really have to add chapter codes to chorus names?

### ISSUE THREAD

**Issue by russkibass** [dbinetti/barberscore-ember#4]
Noticed in groups you have these names

![screen shot 2016-03-16 at 1 16 26](https://cloud.githubusercontent.com/assets/8118886/13821779/67267d12-eb79-11e5-9d03-bd42b9134404.png)

![screen shot 2016-03-16 at 1 14 28](https://cloud.githubusercontent.com/assets/8118886/13821748/42b0e7e2-eb79-11e5-9d58-56aadb25dbb3.png)

Do we really need that? BHS ID are different and so are other factors?

**Comment by dbinetti** [comment]
The BHS does not consider a chorus separately from the chapter.  Thus, you have Sante Fe Springs, instead of Masters of Harmony.  It also means that you can't have choruses change names through time.  

We're going to change that.  So Groups (quartets/choruses, etc.) will be different than chapters.  We'll always refer to groups by their name.
